### ISSUE TITLE
Fails to read service account JSON

### ISSUE THREAD

**Issue by snoozesecurity** [claudiuri/deploy-gae-action#1]
See the below error in the Actions console:

Run claudiuri/deploy-gae-action@v1.2
  with:
Processing service account
  Copy service account
  Activate service account
  ERROR: (gcloud.auth.activate-service-account) Could not read json file /tmp/1596670866089.json: Expecting value: line 1 column 1 (char 0)
  ##[error]Command failed: gcloud auth activate-service-account --key-file /tmp/1596670866089.json

I just copy and pasted the output from the `cat keyfile.json` command.  Should I be doing something different for `SERVICE_ACCOUNT` secret?

**Comment by claudiuri** [comment]
I believe you did not pass the service bill in the correct mandarin in the secret
